### ISSUE TITLE
незачет

### ISSUE THREAD

**Issue by lesyapisha** [vasinkevych/vasinkevych.github.io#1]
Исправить:

1. Вынести сss в отдельный файл. 
2. Писать стили только в css, ни в коем случае не пишем через html атрибуты http://prntscr.com/8tbi6r
3. Вместо тега hr, реализовать подчеркивание с помощью css. Теги  hr, br   считаються устаревшими, их лучше не использовать вообще. 
4. Придерживаться общепринятого форматирования кода http://habrahabr.ru/post/143452/ 
5. Не соответствие макету. Твой основной блок растянут на ширину браузера, нужно ему задать размеры и выровнять по центру.

**Comment by vasinkevych** [comment]
виеконано
