### ISSUE TITLE
незачет js hw5-6

### ISSUE THREAD

**Issue by lesyapisha** [vasinkevych/vasinkevych.github.io#14]
var body = document.querySelector('body');

var startButton = document.createElement('div');
body.appendChild(startButton);
startButton.classList.add('start');
startButton.innerHTML = 'Start Time';
// startButton.addEventListener("click", printNumbersInterval);

var timer = document.createElement('div');
body.appendChild(timer);
timer.innerHTML = '00:00:00:000';

var milliseconds = 0;
var seconds = 0;
var minutes = 0;
var hours = 0;

function printTimer() {

  var time = hours + ':' + minutes + ':' + seconds + ':' + milliseconds;
  timer.innerHTML = time;

  milliseconds++;
  if (milliseconds === 1000) {
    milliseconds = 0;
    seconds++;
  }

  if (seconds === 60) {
    seconds = 0;
    minutes++;
  }

  if (minutes === 60) {
    minutes = 0;
    hours++;
  }
}

printTimer();
function setTime(){
  interval = setInterval(printTimer, 1);
}
setTime();

1. основна помилка в тому, що в тебе оці змінні 
var milliseconds = 0;
var seconds = 0;
var minutes = 0;
var hours = 0; 
щоразу перезаписувалися при кожному виклику функції і щоразу вони перезаписувались в 0, тому їх треба було винести з функції, перший раз ти їх обнуляєш, а далі вже присвоюєш потрібні значення.
2. перезаписується контейнер дів, в який виводиться значення
timer = document.createElement('div');
timer = setInterval(printTimer, 1);
3. setInterval не может запускать функцию каждую 1 милисекунду, потому что для этого должен быть очень мощный компьютер + это заняло бы слишком много процессорного времени
Поэтому setInterval запускает функцию с минимально возможной задержкой, иногда 10, иногда 15 милисекунд и, следовательно, итерации будут проходить медленне

чтобы таймер работал правильно - нужно :

1) Запомнить текущую дату (создать переменную в глобальном скоупе)
2) запустить интервал каждые 10 милисекунд, или 50, чтобы немного снизить нагрузку на процессор
3) внутри функции нужно получать новую дату и отнимать дату, которую мы сохранили в 1) пункте.
4) Конвертировать полученный результат в милисекунды, секунды, минуты и т.д. 
5) обновлять innerHTML нужного элемента

Лучше всего дату сохранять в формате timestamp, чтобы удобно было потом конвертировать.

В сети есть много примеров таймеров, можно подсмотреть какое-нибудь хитрое решение

**Comment by vasinkevych** [comment]
все виправлено. Зроблено кнопку split
