### ISSUE TITLE
незачет

### ISSUE THREAD

**Issue by lesyapisha** [vasinkevych/vasinkevych.github.io#2]
исправить:
1. Файлы .css, .jpg должны лежать в отдельных папках, а не на уровне.
2. (margin-top:5px; margin-left: auto; margin-right:auto;) = (margin:5px auto 0;), не пишем лишние стили. 
3. В качестве единиц измерения рекомендуеться использовать px или %.

**Comment by vasinkevych** [comment]
виправив
