### ISSUE TITLE
незачет дз3

### ISSUE THREAD

**Issue by lesyapisha** [vasinkevych/vasinkevych.github.io#7]
1. Основному блоку задать фиксированную ширину и выровнять по центру http://prntscr.com/8y6v96 или если ты решил делать этот блок резиновым, нужно чтоб .content тоже был резиновым и выравнивался оп центру.
2. Наложение 2-х бордеров. нужно у верхнего li отменить значение бордер, это можно сделать с помощью псевдокласса :first-child.
3. А что если нам нужно будет изменить название пункта меню и оно окажеться длиннее 145px?
http://prntscr.com/8y70xr, а должно быть так http://prntscr.com/8y718u
4. Поток не восстановлен div class="container". Разберись еще раз как это работает.
5. После нажатия появляеться выделение, его не должно быть http://prntscr.com/8y4763, http://prntscr.com/8y47yd

**Comment by vasinkevych** [comment]
виправлено все крім п.2
